# Generated by Django 5.1.7 on 2025-08-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('paddress', models.CharField(max_length=122)),
                ('dob', models.DateField()),
                ('branch', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
