# Generated by Django 5.1.7 on 2025-08-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_apply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apply',
            new_name='Applicant',
        ),
    ]
