# Generated by Django 5.1.7 on 2025-09-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_apply_applicant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Feedback',
        ),
    ]
